version: '2'
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.1
services:
  kqueen_mail:
    image: modularitycontainers/postfix
    ports:
      - 127.0.0.1:25:10025
    volumes:
      - /var/spool/postfix:/var/spool/postfix
      - /var/spool/mail:/var/spool/mail
    environment:
      MYHOSTNAME: 'localhost'
